### ISSUE TITLE
i downt understand dis libry

### ISSUE THREAD

**Issue by Shakyamuni177te** [mssalvo/allmovie#1]
What does it do, m8?

**Comment by mssalvo** [comment]
And a simple library that integrates Api Deezer
It provides a set of custom controls and a series of functions that allow you to interact processed with api deezer as research pieces, authors, album
the characteristic that distinguishes it, is that unlike plugin static (that do not allow to change the layout) it is fully customizable, default has little! for living needs your html
example,
suppose you want to be included in a deezer api, and we wanted a custom layout the play button at the top right, and the progress bar at the bottom and maybe the image of the author in the middle of the page with this library all this and you can just show him the elements html

the library and still in the development phase
you can find a simple example in the directory allmovie.html
sorry  writing errors Text translated by Google

**Comment by Shakyamuni177te** [comment]
An extension to the Deezer music API.
